name: aplikasi_keuangan
description: "Aplikasi Keuangan Pribadi Modern dengan Flutter"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  flutter_riverpod: ^2.5.1
  
  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Secure Storage
  flutter_secure_storage: ^9.2.2
  
  # Biometric Authentication
  local_auth: ^2.3.0
  
  # Charts
  fl_chart: ^0.69.0
  
  # Animations
  flutter_animate: ^4.5.0
  
  # Icons & SVG
  flutter_svg: ^2.0.10+1
  
  # Date & Currency Formatting
  intl: ^0.19.0
  
  # Navigation
  go_router: ^14.6.2
  
  # UUID Generator
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
